from machine import Pin
import time

p1 = Pin(23, Pin.OUT)
p2 = Pin(22, Pin.OUT)
p3 = Pin(21, Pin.OUT)
p4 = Pin(19, Pin.OUT)
p5 = Pin(18, Pin.OUT)
p6 = Pin(5, Pin.OUT)
p7 = Pin(4, Pin.OUT)
p8 = Pin(2, Pin.OUT)
s1 = Pin(34, Pin.IN)
s2 = Pin(35, Pin.IN)
s3 = Pin(32, Pin.IN)
s4 = Pin(33, Pin.IN)

while True:
    if s1.value()==1:
        p4.on()
        p5.on()
        time.sleep(.5)
        p4.off()
        p5.off()
        p3.on()
        p6.on()
        time.sleep(.5)
        p3.off()
        p6.off()
        p2.on()
        p7.on()
        time.sleep(.5)
        p2.off()
        p7.off()
        p1.on()
        p8.on()
        time.sleep(.5)
        p1.off()
        p8.off()

    if s2.value()==1:
        p1.on()
        p8.on()
        time.sleep(.5)
        p1.off()
        p8.off()
        p3.on()
        p6.on()
        time.sleep(.5)
        p3.off()
        p6.off()
        p4.on()
        p5.on()
        time.sleep(.5)
        p4.off()
        p5.off()
        p3.on()
        p6.on()
        time.sleep(.5)
        p3.off()
        p6.off()
        p2.on()
        p7.on()
        time.sleep(.5)
        p2.off()
        p7.off()
        p1.on()
        p8.on()
        time.sleep(.5)
        p1.off()
        p8.off()
        time.sleep(.5)

    if s3.value()==1:
        p1.on()
        time.sleep(.5)
        p1.off()
        p2.on()
        time.sleep(.5)
        p2.off()
        p3.on()
        time.sleep(.5)
        p3.off()
        p4.on()
        time.sleep(.5)
        p4.off()
        p5.on()
        time.sleep(.5)
        p5.off()
        p6.on()
        time.sleep(.5)
        p6.off()
        p7.on()
        time.sleep(.5)
        p7.off()
        p8.on()
        time.sleep(.5)
        p8.off()
        p7.on()
        time.sleep(.5)
        p7.off()
        p6.on()
        time.sleep(.5)
        p6.off()
        p5.on()
        time.sleep(.5)
        p5.off()
        p4.on()
        time.sleep(.5)
        p4.off()
        p3.on()
        time.sleep(.5)
        p3.off()
        p2.on()
        time.sleep(.5)
        p2.off()
        p1.on()
        time.sleep(.5)
        p1.off()

    if s4.value()==1:
        p1.on()
        p3.on()
        p5.on()
        p7.on()
        time.sleep(.5)
        p1.off()
        p3.off()
        p5.off()
        p7.off()
        p2.on()
        p4.on()
        p6.on()
        p8.on()
        time.sleep(.5)
        p2.off()
        p4.off()
        p6.off()
        p8.off()

    if s1.value()==0:
        p1.off()
        p2.off()
        p3.off()
        p4.off()
        p5.off()
        p6.off()
        p7.off()
        p8.off()

    if s2.value()==0:
        p1.off()
        p2.off()
        p3.off()
        p4.off()
        p5.off()
        p6.off()
        p7.off()
        p8.off()
        
    if s3.value()==0:
        p1.off()
        p2.off()
        p3.off()
        p4.off()
        p5.off()
        p6.off()
        p7.off()
        p8.off()

    if s4.value()==0:
        p1.off()
        p2.off()
        p3.off()
        p4.off()
        p5.off()
        p6.off()
        p7.off()
        p8.off()



    

    